Filter settings based on Engine
ClickHouse/dbt-clickhouse pull request #367
Opened 2024-10-11 16:16 UTC by shachibista

This PR introduces a feature that ignores settings that are not compatible with the Engine. More details in this issue: https://github.com/ClickHouse/dbt-clickhouse/issues/366

## Checklist
- [x ] A human-readable description of the changes was provided to include in CHANGELOG

2024-10-11 16:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/dbt-clickhouse?pullRequest=367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/dbt-clickhouse?pullRequest=367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/dbt-clickhouse?pullRequest=367) it.</sub>

2024-11-03 12:24 UTC, BentsiLeviav commented
@genzgd suggested changing it from a white list to a black list (remove settings we identified as not relevant for this engine), and in case we face a new engine, pass the settings as is.

@shachibista would you mind changing the logic to support this?

2025-01-02 13:34 UTC, BentsiLeviav requested changes
Let me know WDYT about changing it to a black list instead of a white list

2025-01-06 23:14 UTC, shachibista commented
> Let me know WDYT about changing it to a black list instead of a white list

I don't personally agree with a black-list since:

1. It also requires some maintainance so the above reasoning about maintainence is moot.
2. It requires that invalid settings to be [discovered by users](https://github.com/ClickHouse/dbt-clickhouse/issues/366#issuecomment-2573740072) for each engine, forcing them to wait for the next release of the library.

However I have made the requested changes if it feels right to you since the original issue I was trying to solve was solved using another method (wrote own observability package, for posterity) and as such this issue is no longer important to me at this moment.

Hope that helps!

2025-01-07 08:29 UTC, BentsiLeviav commented
> It also requires some maintainance so the above reasoning about maintainence is moot.

There is a significant difference between updating the extensive settings dictionary with every ClickHouse (CH) release and allowing users to be completely blocked from using new configurations until we update it. By addressing mismatched settings, we can handle far fewer scenarios compared to CH introducing tens of new configurations every year.

> forcing them to wait for the next release of the library.

In my opinion, this approach is better than blocking the entire community from accessing new features or settings, which happens with every release.


> However I have made the requested changes if it feels right to you since the original issue I was trying to solve was solved using another method (wrote own observability package, for posterity) and as such this issue is no longer important to me at this moment.



Thank you for changing the code. Your efforts are sincerely appreciated and not taken for granted.

2025-01-07 09:16 UTC, BentsiLeviav commented on dbt/adapters/clickhouse/impl.py
> +        if engine not in IGNORED_SETTINGS:
The `IGNORED_SETTINGS` dict has only 2 keys (`S3` and `Memory`), therefore, any engine provided to this function will return an empty dict (`filtered_settings`). 

In case we don't have any "black list settings" for this engine, we should return the settings as is, no?

2025-01-07 09:19 UTC, BentsiLeviav commented on dbt/adapters/clickhouse/impl.py
> +        if engine not in IGNORED_SETTINGS:
We can remove this if clause, no? because if the engine is not in `IGNORED_SETTINGS`, we will iterate over an empty list and return the populated `filtered_settings` with the original `settings` values

2025-01-08 16:20 UTC, shachibista commented on dbt/adapters/clickhouse/impl.py
> +        if engine not in IGNORED_SETTINGS:
You're right 👍

2025-01-09 08:34 UTC, BentsiLeviav approved these changes

2025-01-09 08:43 UTC, merged