Feature/create indexes
ClickHouse/dbt-clickhouse pull request #397
Opened 2024-12-03 03:54 UTC by stephen-up

## Summary
Provides a way to create indexes for your tables.

2024-12-03 03:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/dbt-clickhouse?pullRequest=397) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/dbt-clickhouse?pullRequest=397) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/dbt-clickhouse?pullRequest=397) it.</sub>

2025-01-05 10:08 UTC, BentsiLeviav requested changes
Hi @stephen-up 

Thank you for your contribution!
Could you please take care of the following:
* Please sign the CLA with @stephennancekivell (as this user committed the code)
* Could you please add an indication to the project readme file? We usually do that for features introducing configs.

2025-01-05 21:57 UTC, stephen-up commented
Hi @BentsiLeviav. Sorry all sorted. Thanks for merging.

2025-01-06 08:17 UTC, BentsiLeviav commented
I added an indication to the readme file.

2025-01-06 08:31 UTC, BentsiLeviav approved these changes

2025-01-06 08:31 UTC, merged